name: CI CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker
        run: docker build -t manualaz:latest .
      - name: List images
        run: docker images
      - name: Run
        run: docker run manualaz --name manualaz
      - name: List containers
        run: docker ps -a
