name: CI CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build image
        run: docker build -t manualaz:latest .
      - name: List images
        run: docker images
      - name: Run
        run: docker run -d -p 8080:80 manualaz
      - name: List containers
        run: docker ps -a
      - name: Call
        run: curl http://localhost:8080/index.html
